#!/bin/bash

echo "🚀 Deploying to PythonAnywhere..."

echo "📋 Manual steps you need to do in PythonAnywhere:"
echo ""
echo "1. Go to PythonAnywhere Web tab"
echo "2. Add new web app → Manual config → Python 3.10"
echo "3. In WSGI file, delete all content and paste:"
echo ""
echo "import sys"
echo "import os"
echo ""
echo "project_home = '/home/yourusername/TVB_Workshops'"
echo "if project_home not in sys.path:"
echo "    sys.path.insert(0, project_home)"
echo ""
echo "os.environ['FLASK_ENV'] = 'production'"
echo ""
echo "from waitinglist_app import app as application"
echo ""
echo "4. Add static files:"
echo "   URL: /static/"
echo "   Directory: /home/yourusername/TVB_Workshops/static/"
echo ""
echo "5. Set environment variables:"
echo "   STRIPE_SECRET_KEY = sk_test_51SMPehGf9P1kk0BnS9ypd2cPraRWqPfQtJHhPTcpcpuQHIkBxVjcRy1ubNJvkwCBkeYEZ5m9Es5gMWUZfxXonObj00ggxVBZmU"
echo "   STRIPE_PUBLISHABLE_KEY = pk_test_51SMPehGf9P1kk0Bn6fixDPguXM8bSxEJy6F7wTmzQB7mVQtzEkFBpqg9xenscQDVArnvwfgBBUEn4IRVKNEUEBgj000B6a9RPe"
echo "   STRIPE_PRODUCT_ID = prod_TJ1v4b9S6EUxIQ"
echo "   FLASK_ENV = production"
echo ""
echo "6. Click Reload button"
echo ""
echo "✅ Your app will be live at: https://yourusername.pythonanywhere.com"
echo ""
echo "🔧 Commands to run in PythonAnywhere Bash console:"
echo "cd ~"
echo "git clone https://github.com/yyqfrank420/polymarketapp.git TVB_Workshops"
echo "cd TVB_Workshops"
echo "pip3.10 install --user -r requirements.txt"
echo ""
echo "Done! 🎉"
